"""Auto-retarget planner.

Given an asset directory (or an existing :class:`AuditReport`) and a
target engine, emit an :class:`EditGraph` populated with retarget ops
that, when evaluated, would resolve the cross-engine diagnostics.

Design choices:

* **Diagnostics-driven, not heuristic-driven.** The planner reads issues
  from the cross-engine audit rules and inserts one operation per issue
  type. It never invents extra fix-up steps.
* **Stable ordering.** Axis swap → units → pivot → naming. This is the
  order an Unreal/Unity import pipeline would expect: change the basis
  first, scale within the new basis, then re-pivot, then apply names.
* **Idempotent if the asset is already retargeted.** If no retarget
  diagnostics fire, the resulting graph is empty.
* **Standalone EditGraph.** The planner returns a graph; persisting it
  is the caller's job (HTTP / MCP / UI all decide independently).
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from ..audit.report import AuditIssue, AuditReport
from ..audit.runner import audit_asset
from ..authoring.schema import EditGraph, OperationNode
from ..manifest import EngineTarget, manifest_exists, read_manifest
from .presets import retarget_rules_for_preset, unity_retarget_preset, unreal_retarget_preset
from .profiles import EngineConventions, get_profile


_PRESETS_BY_TARGET = {
    "unity": unity_retarget_preset,
    "unreal": unreal_retarget_preset,
}


def _node_id(prefix: str, used: set[str]) -> str:
    candidate = prefix
    counter = 1
    while candidate in used:
        counter += 1
        candidate = f"{prefix}_{counter}"
    used.add(candidate)
    return candidate


def plan_retarget_graph_from_diagnostics(
    issues: Iterable[AuditIssue],
    *,
    target_engine: str,
    base_name: str | None = None,
    graph_id: str | None = None,
    graph_name: str | None = None,
    asset_id: str | None = None,
    base_asset_path: str | None = None,
    output_path: str | None = None,
) -> EditGraph:
    """Build an EditGraph from a flat list of audit issues."""

    profile = get_profile(target_engine)
    issue_codes = {issue.code for issue in issues if issue.rule.startswith("retarget.")}

    nodes: list[OperationNode] = []
    used_ids: set[str] = set()

    if "axis_mismatch_assumed" in issue_codes:
        nodes.append(
            OperationNode(
                id=_node_id("axis", used_ids),
                kind="retarget_axis",
                label=f"Axis → {profile.label}",
                params={"from": "gltf_canonical", "to": target_engine},
            )
        )
    if "units_scale_required" in issue_codes:
        factor = 1.0 / profile.units_to_meters
        nodes.append(
            OperationNode(
                id=_node_id("units", used_ids),
                kind="retarget_units",
                label=f"Units (factor {factor:g})",
                params={"factor": factor, "to": target_engine},
            )
        )
    if "pivot_not_at_base" in issue_codes:
        nodes.append(
            OperationNode(
                id=_node_id("pivot", used_ids),
                kind="retarget_pivot_for_engine",
                label="Pivot at base",
                params={"to": target_engine},
            )
        )
    if (
        "static_mesh_prefix_missing" in issue_codes
        or "material_prefix_missing" in issue_codes
    ) and profile.naming.static_mesh_prefix:
        nodes.append(
            OperationNode(
                id=_node_id("naming", used_ids),
                kind="retarget_apply_naming",
                label=f"Naming → {profile.label}",
                params={"to": target_engine, "base_name": base_name or "Asset"},
            )
        )

    return EditGraph(
        graph_id=graph_id or f"retarget-{target_engine}",
        asset_id=asset_id,
        name=graph_name or f"Auto-retarget for {profile.label}",
        description=(
            f"Generated by GhostForge retarget planner from "
            f"{len(issue_codes)} cross-engine diagnostics."
        ),
        base_asset_path=base_asset_path,
        output_path=output_path,
    ).with_nodes(nodes)


def plan_retarget_graph_for_asset(
    asset_dir: str | Path,
    *,
    target_engine: str,
    base_name: str | None = None,
    graph_id: str | None = None,
    graph_name: str | None = None,
    output_path: str | None = None,
    run_gltf_validator: bool = False,
) -> tuple[EditGraph, AuditReport]:
    """Run an audit then build a retarget graph from the diagnostics.

    Returns the graph plus the underlying :class:`AuditReport` so the
    caller can persist it or surface it in the UI alongside the graph.
    """

    asset_path = Path(asset_dir)
    if not manifest_exists(asset_path):
        raise FileNotFoundError(f"No asset_manifest.json at {asset_path}")
    if target_engine not in _PRESETS_BY_TARGET:
        raise ValueError(
            f"unsupported target_engine {target_engine!r}; expected one of "
            f"{sorted(_PRESETS_BY_TARGET)}"
        )

    preset_factory = _PRESETS_BY_TARGET[target_engine]
    report = audit_asset(
        asset_path,
        preset=preset_factory(),
        rules=retarget_rules_for_preset(target_engine),
        run_gltf_validator=run_gltf_validator,
        persist=False,
    )
    manifest = read_manifest(asset_path)
    graph = plan_retarget_graph_from_diagnostics(
        report.issues,
        target_engine=target_engine,
        base_name=base_name or manifest.name or manifest.asset_id,
        graph_id=graph_id or f"retarget-{manifest.asset_id}-{target_engine}",
        graph_name=graph_name,
        asset_id=manifest.asset_id,
        base_asset_path=str((asset_path / "mesh.glb").resolve())
        if (asset_path / "mesh.glb").exists()
        else None,
        output_path=output_path,
    )
    return graph, report


__all__ = [
    "plan_retarget_graph_for_asset",
    "plan_retarget_graph_from_diagnostics",
]
